-- MySQL Script generated by MySQL Workbench
-- 11/05/15 17:36:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EMPLOYEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLOYEE` (
  `EmployeeNo` CHAR(4) NOT NULL COMMENT '',
  `SSNum` CHAR(9) NOT NULL COMMENT '',
  `Salary` DECIMAL(9,2) NOT NULL COMMENT '',
  `HireDate` DATE NOT NULL COMMENT '',
  `DateofBirth` DATE NOT NULL COMMENT '',
  `JobID` CHAR(4) NOT NULL COMMENT '',
  PRIMARY KEY (`EmployeeNo`)  COMMENT '',
  CONSTRAINT `fk_EMPLOYEE_PERSON1`
    FOREIGN KEY (`EmployeeNo`)
    REFERENCES `mydb`.`PERSON` (`PersonNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROPERTY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROPERTY` (
  `AddressID` INT NOT NULL COMMENT '',
  `PropTypeNo` CHAR(4) NOT NULL COMMENT '',
  `Rent` DECIMAL(8,2) NOT NULL COMMENT '',
  `Rooms` INT NOT NULL COMMENT '',
  `AgentNo` CHAR(4) NULL COMMENT '',
  `OwnerNo` CHAR(4) NOT NULL COMMENT '',
  PRIMARY KEY (`AddressID`)  COMMENT '',
  INDEX `fk_PROPERTY_PERSON1_idx` (`OwnerNo` ASC)  COMMENT '',
  INDEX `fk_PROPERTY_EMPLOYEE1_idx` (`AgentNo` ASC)  COMMENT '',
  CONSTRAINT `fk_PROPERTY_PERSON1`
    FOREIGN KEY (`OwnerNo`)
    REFERENCES `mydb`.`PERSON` (`PersonNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROPERTY_EMPLOYEE1`
    FOREIGN KEY (`AgentNo`)
    REFERENCES `mydb`.`EMPLOYEE` (`EmployeeNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ADDRESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ADDRESS` (
  `AddressID` INT NULL COMMENT '',
  `Street` VARCHAR(45) NOT NULL COMMENT '',
  `City` VARCHAR(35) NOT NULL COMMENT '',
  `State` CHAR(2) NULL COMMENT '',
  `PostCode` VARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`AddressID`)  COMMENT '',
  CONSTRAINT `fk_ADDRESS_PROPERTY1`
    FOREIGN KEY (`AddressID`)
    REFERENCES `mydb`.`PROPERTY` (`AddressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERSON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERSON` (
  `PersonNo` CHAR(4) NOT NULL COMMENT '',
  `FName` VARCHAR(20) NOT NULL COMMENT '',
  `LName` VARCHAR(25) NOT NULL COMMENT '',
  `AddressID` INT NOT NULL COMMENT '',
  `PhoneNumber` VARCHAR(10) NULL COMMENT '',
  `CellPhone` VARCHAR(10) NOT NULL COMMENT '',
  `Gender` CHAR(2) NOT NULL COMMENT '',
  `emailAddress` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`PersonNo`)  COMMENT '',
  INDEX `fk_PERSON_ADDRESS_idx` (`AddressID` ASC)  COMMENT '',
  CONSTRAINT `fk_PERSON_ADDRESS`
    FOREIGN KEY (`AddressID`)
    REFERENCES `mydb`.`ADDRESS` (`AddressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENT` (
  `ClientNo` CHAR(4) NOT NULL COMMENT '',
  `PrefType` INT NOT NULL COMMENT '',
  `MaxRent` DECIMAL(6,2) NOT NULL COMMENT '',
  `JoinedOn` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`ClientNo`)  COMMENT '',
  CONSTRAINT `fk_CLIENT_PERSON1`
    FOREIGN KEY (`ClientNo`)
    REFERENCES `mydb`.`PERSON` (`PersonNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LEASE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LEASE` (
  `LeaseNo` INT NOT NULL COMMENT '',
  `StartDate` DATE NOT NULL COMMENT '',
  `EndDate` DATE NOT NULL COMMENT '',
  `Duration` VARCHAR(45) NOT NULL COMMENT '',
  `MonthRent` DECIMAL(5,2) NOT NULL COMMENT '',
  `DateSigned` DATE NOT NULL COMMENT '',
  `ClientNo` CHAR(4) NOT NULL COMMENT '',
  `AddressID` INT NOT NULL COMMENT '',
  PRIMARY KEY (`LeaseNo`)  COMMENT '',
  INDEX `fk_LEASE_CLIENT1_idx` (`ClientNo` ASC)  COMMENT '',
  INDEX `fk_LEASE_PROPERTY1_idx` (`AddressID` ASC)  COMMENT '',
  CONSTRAINT `fk_LEASE_CLIENT1`
    FOREIGN KEY (`ClientNo`)
    REFERENCES `mydb`.`CLIENT` (`ClientNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LEASE_PROPERTY1`
    FOREIGN KEY (`AddressID`)
    REFERENCES `mydb`.`PROPERTY` (`AddressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
